import { Player, Tournament } from '../types/chess';

export const INITIAL_PLAYERS: Omit<Player, 'id'>[] = [
  {
    name: 'Luis Paulo Supi',
    title: 'GM',
    birthDate: '1996-05-18',
    gender: 'M',
    fideId: '2119934',
    cbxId: '14820',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2119934',
    cbxUrl: 'https://www.cbx.org.br/jogador/14820',
    ratingFide: 2580,
    ratingFideStandard: 2580,
    ratingFideRapid: 2540,
    ratingFideBlitz: 2635,
    ratingCbx: 2610,
    ratingCbxStandard: 2610,
    ratingCbxRapid: 2590,
    ratingCbxBlitz: 2670,
    club: 'Clube de Xadrez de Catanduva',
    notes: 'Grande Mestre Internacional Brasileiro, ex-campeão pan-americano.'
  },
  {
    name: 'Alexandr Fier',
    title: 'GM',
    birthDate: '1988-03-11',
    gender: 'M',
    fideId: '2107138',
    cbxId: '10293',
    country: 'Brasil',
    state: 'PR',
    fideUrl: 'https://ratings.fide.com/profile/2107138',
    cbxUrl: 'https://www.cbx.org.br/jogador/10293',
    ratingFide: 2595,
    ratingFideStandard: 2595,
    ratingFideRapid: 2570,
    ratingFideBlitz: 2640,
    ratingCbx: 2630,
    ratingCbxStandard: 2630,
    ratingCbxRapid: 2615,
    ratingCbxBlitz: 2680,
    club: 'Clube de Xadrez de Curitiba',
    notes: 'Multi-campeão Brasileiro Absoluto e olímpico.'
  },
  {
    name: 'Juliana Sayumi Terao',
    title: 'WGM',
    birthDate: '1991-07-12',
    gender: 'F',
    fideId: '2113200',
    cbxId: '12450',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2113200',
    cbxUrl: 'https://www.cbx.org.br/jogador/12450',
    ratingFide: 2280,
    ratingFideStandard: 2280,
    ratingFideRapid: 2230,
    ratingFideBlitz: 2295,
    ratingCbx: 2320,
    ratingCbxStandard: 2320,
    ratingCbxRapid: 2285,
    ratingCbxBlitz: 2340,
    club: 'Clube Atlético Paulistano',
    notes: 'Heptacampeã Brasileira Feminina de Xadrez.'
  },
  {
    name: 'Kathie Goulart Librelato',
    title: 'WIM',
    birthDate: '1998-07-27',
    gender: 'F',
    fideId: '2124571',
    cbxId: '18932',
    country: 'Brasil',
    state: 'SC',
    fideUrl: 'https://ratings.fide.com/profile/2124571',
    cbxUrl: 'https://www.cbx.org.br/jogador/18932',
    ratingFide: 2210,
    ratingFideStandard: 2210,
    ratingFideRapid: 2165,
    ratingFideBlitz: 2220,
    ratingCbx: 2250,
    ratingCbxStandard: 2250,
    ratingCbxRapid: 2210,
    ratingCbxBlitz: 2260,
    club: 'Associação Criciumense de Xadrez',
    notes: 'Mestre Internacional Feminina e integrante da equipe olímpica.'
  },
  {
    name: 'Krikor Sevag Mekhitarian',
    title: 'GM',
    birthDate: '1986-11-15',
    gender: 'M',
    fideId: '2107669',
    cbxId: '11054',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2107669',
    cbxUrl: 'https://www.cbx.org.br/jogador/11054',
    ratingFide: 2545,
    ratingFideStandard: 2545,
    ratingFideRapid: 2520,
    ratingFideBlitz: 2590,
    ratingCbx: 2570,
    ratingCbxStandard: 2570,
    ratingCbxRapid: 2550,
    ratingCbxBlitz: 2620,
    club: 'Clube Hebraica SP',
    notes: 'Bicampeão Brasileiro Absoluto e criador de conteúdo.'
  },
  {
    name: 'Enzo Federzoni Sakai',
    title: 'FM',
    birthDate: '2005-02-14',
    gender: 'M',
    fideId: '2138904',
    cbxId: '24110',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2138904',
    cbxUrl: 'https://www.cbx.org.br/jogador/24110',
    ratingFide: 2360,
    ratingFideStandard: 2360,
    ratingFideRapid: 2315,
    ratingFideBlitz: 2380,
    ratingCbx: 2390,
    ratingCbxStandard: 2390,
    ratingCbxRapid: 2350,
    ratingCbxBlitz: 2420,
    club: 'CXSP',
    notes: 'Destaque nas categorias de base e mestre FIDE.'
  },
  {
    name: 'Julia Alboredo',
    title: 'WIM',
    birthDate: '1993-01-12',
    gender: 'F',
    fideId: '2118334',
    cbxId: '15640',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2118334',
    cbxUrl: 'https://www.cbx.org.br/jogador/15640',
    ratingFide: 2240,
    ratingFideStandard: 2240,
    ratingFideRapid: 2200,
    ratingFideBlitz: 2255,
    ratingCbx: 2280,
    ratingCbxStandard: 2280,
    ratingCbxRapid: 2240,
    ratingCbxBlitz: 2290,
    club: 'Clube de Xadrez de Osasco',
    notes: 'Campeã Brasileira Feminina de 2021.'
  },
  {
    name: 'Rafael Duailibe Leitão',
    title: 'GM',
    birthDate: '1979-12-28',
    gender: 'M',
    fideId: '2100290',
    cbxId: '8020',
    country: 'Brasil',
    state: 'MA',
    fideUrl: 'https://ratings.fide.com/profile/2100290',
    cbxUrl: 'https://www.cbx.org.br/jogador/8020',
    ratingFide: 2600,
    ratingFideStandard: 2600,
    ratingFideRapid: 2560,
    ratingFideBlitz: 2620,
    ratingCbx: 2640,
    ratingCbxStandard: 2640,
    ratingCbxRapid: 2610,
    ratingCbxBlitz: 2665,
    club: 'Academia Rafael Leitão',
    notes: 'Heptacampeão Brasileiro Absoluto e Grande Mestre desde os 18 anos.'
  },
  {
    name: 'Guilherme Deola Borges',
    title: 'CMN',
    birthDate: '1995-08-20',
    gender: 'M',
    fideId: '2139045',
    cbxId: '31520',
    country: 'Brasil',
    state: 'SC',
    fideUrl: 'https://ratings.fide.com/profile/2139045',
    cbxUrl: 'https://www.cbx.org.br/jogador/31520',
    ratingFide: 2045,
    ratingFideStandard: 2045,
    ratingFideRapid: 2020,
    ratingFideBlitz: 2090,
    ratingCbx: 2080,
    ratingCbxStandard: 2080,
    ratingCbxRapid: 2060,
    ratingCbxBlitz: 2110,
    club: 'Clube de Xadrez de Florianópolis',
    notes: 'Candidato a Mestre Nacional pela Confederação Brasileira de Xadrez.'
  },
  {
    name: 'Lucas Henrique de Souza',
    title: 'AIM',
    birthDate: '2001-04-12',
    gender: 'M',
    fideId: '2148120',
    cbxId: '42180',
    country: 'Brasil',
    state: 'MG',
    fideUrl: 'https://ratings.fide.com/profile/2148120',
    cbxUrl: 'https://www.cbx.org.br/jogador/42180',
    ratingFide: 1910,
    ratingFideStandard: 1910,
    ratingFideRapid: 1940,
    ratingFideBlitz: 2015,
    ratingCbx: 1950,
    ratingCbxStandard: 1950,
    ratingCbxRapid: 1980,
    ratingCbxBlitz: 2030,
    club: 'Associação Mineira de Xadrez',
    notes: 'Arena International Master (AIM) pela FIDE Online Arena.'
  },
  {
    name: 'Beatriz Vasconcelos',
    title: 'AFM',
    birthDate: '2003-10-18',
    gender: 'F',
    fideId: '2151090',
    cbxId: '44510',
    country: 'Brasil',
    state: 'CE',
    fideUrl: 'https://ratings.fide.com/profile/2151090',
    cbxUrl: 'https://www.cbx.org.br/jogador/44510',
    ratingFide: 1820,
    ratingFideStandard: 1820,
    ratingFideRapid: 1850,
    ratingFideBlitz: 1890,
    ratingCbx: 1860,
    ratingCbxStandard: 1860,
    ratingCbxRapid: 1880,
    ratingCbxBlitz: 1910,
    club: 'Clube de Xadrez de Fortaleza',
    notes: 'Arena FIDE Master (AFM), destaque cearense universitário.'
  },
  {
    name: 'Gabriel de Oliveira Santos',
    title: 'FM',
    birthDate: '2008-01-22',
    gender: 'M',
    fideId: '2160341',
    cbxId: '48920',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2160341',
    cbxUrl: 'https://www.cbx.org.br/jogador/48920',
    ratingFide: 2315,
    ratingFideStandard: 2315,
    ratingFideRapid: 2290,
    ratingFideBlitz: 2340,
    ratingCbx: 2330,
    ratingCbxStandard: 2330,
    ratingCbxRapid: 2300,
    ratingCbxBlitz: 2350,
    club: 'Clube de Xadrez de São Paulo',
    notes: 'Mestre FIDE, campeão brasileiro juvenil Sub-18 e destaque Sub-20.'
  },
  {
    name: 'Mariana Franco Xavier',
    title: 'WFM',
    birthDate: '2007-06-18',
    gender: 'F',
    fideId: '2162890',
    cbxId: '49810',
    country: 'Brasil',
    state: 'RS',
    fideUrl: 'https://ratings.fide.com/profile/2162890',
    cbxUrl: 'https://www.cbx.org.br/jogador/49810',
    ratingFide: 2190,
    ratingFideStandard: 2190,
    ratingFideRapid: 2150,
    ratingFideBlitz: 2210,
    ratingCbx: 2210,
    ratingCbxStandard: 2210,
    ratingCbxRapid: 2180,
    ratingCbxBlitz: 2230,
    club: 'Metrópole Xadrez Clube',
    notes: 'Mestre FIDE Feminina, integrante da seleção jovem e campeã estadual.'
  },
  {
    name: 'Henrique Castro Peixoto',
    title: 'CM',
    birthDate: '2013-05-10',
    gender: 'M',
    fideId: '2171044',
    cbxId: '52400',
    country: 'Brasil',
    state: 'RJ',
    fideUrl: 'https://ratings.fide.com/profile/2171044',
    cbxUrl: 'https://www.cbx.org.br/jogador/52400',
    ratingFide: 1920,
    ratingFideStandard: 1920,
    ratingFideRapid: 1880,
    ratingFideBlitz: 1940,
    ratingCbx: 1940,
    ratingCbxStandard: 1940,
    ratingCbxRapid: 1900,
    ratingCbxBlitz: 1950,
    club: 'Clube de Xadrez Guanabara',
    notes: 'Candidato a Mestre FIDE, campeão brasileiro escolar Sub-14.'
  },
  {
    name: 'Laura Beatriz Nogueira',
    title: 'WCM',
    birthDate: '2012-11-04',
    gender: 'F',
    fideId: '2174512',
    cbxId: '53110',
    country: 'Brasil',
    state: 'PR',
    fideUrl: 'https://ratings.fide.com/profile/2174512',
    cbxUrl: 'https://www.cbx.org.br/jogador/53110',
    ratingFide: 1845,
    ratingFideStandard: 1845,
    ratingFideRapid: 1810,
    ratingFideBlitz: 1860,
    ratingCbx: 1860,
    ratingCbxStandard: 1860,
    ratingCbxRapid: 1830,
    ratingCbxBlitz: 1870,
    club: 'Clube de Xadrez de Curitiba',
    notes: 'Candidata a Mestre Feminina FIDE, campeã pan-americana da juventude.'
  },
  {
    name: 'Matheus Ribeiro Silveira',
    title: 'Sem Título',
    birthDate: '2017-03-15',
    gender: 'M',
    fideId: '2180120',
    cbxId: '56230',
    country: 'Brasil',
    state: 'SC',
    fideUrl: 'https://ratings.fide.com/profile/2180120',
    cbxUrl: 'https://www.cbx.org.br/jogador/56230',
    ratingFide: 1620,
    ratingFideStandard: 1620,
    ratingFideRapid: 1580,
    ratingFideBlitz: 1610,
    ratingCbx: 1640,
    ratingCbxStandard: 1640,
    ratingCbxRapid: 1600,
    ratingCbxBlitz: 1630,
    club: 'Clube de Xadrez de Joinville',
    notes: 'Revelação catarinense Sub-10, campeão sul-brasileiro da categoria.'
  },
  {
    name: 'Sofia Mendes Albuquerque',
    title: 'Sem Título',
    birthDate: '2016-08-20',
    gender: 'F',
    fideId: '2181432',
    cbxId: '56890',
    country: 'Brasil',
    state: 'SP',
    fideUrl: 'https://ratings.fide.com/profile/2181432',
    cbxUrl: 'https://www.cbx.org.br/jogador/56890',
    ratingFide: 1540,
    ratingFideStandard: 1540,
    ratingFideRapid: 1500,
    ratingFideBlitz: 1530,
    ratingCbx: 1560,
    ratingCbxStandard: 1560,
    ratingCbxRapid: 1520,
    ratingCbxBlitz: 1550,
    club: 'Clube de Xadrez de Santos',
    notes: 'Campeã paulista Sub-10 Feminino.'
  }
];

export const INITIAL_TOURNAMENTS: Omit<Tournament, 'id'>[] = [
  {
    name: 'Aberto do Brasil FBX Memorial 2026',
    city: 'São Paulo',
    state: 'SP',
    startDate: '2026-11-14',
    endDate: '2026-11-17',
    rounds: 6,
    timeControl: 'Pensado (90m + 30s de acréscimo)',
    type: 'standard',
    status: 'Planejado',
    arbiters: 'AI Carlos Calleros, AN Roberto Viana',
    organizer: 'Federação Brasileira de Xadrez',
    participants: [],
    standings: []
  },
  {
    name: 'Campeonato Sul-Brasileiro Rápido & Blitz',
    city: 'Curitiba',
    state: 'PR',
    startDate: '2026-09-05',
    endDate: '2026-09-06',
    rounds: 9,
    timeControl: 'Rápido (15m + 10s)',
    type: 'rapid',
    status: 'Finalizado',
    arbiters: 'AI Marco Antonio Asbahr',
    organizer: 'Federação Paranaense de Xadrez',
    participants: [],
    standings: [
      {
        playerId: 'seed-1',
        playerName: 'Alexandr Fier',
        title: 'GM',
        fideId: '2107138',
        points: 8.0,
        rank: 1,
        buchholz: 49.5,
        sonnebornBerger: 43.5,
        wins: 7
      },
      {
        playerId: 'seed-2',
        playerName: 'Luis Paulo Supi',
        title: 'GM',
        fideId: '2119934',
        points: 7.5,
        rank: 2,
        buchholz: 50.0,
        sonnebornBerger: 41.0,
        wins: 7
      },
      {
        playerId: 'seed-3',
        playerName: 'Krikor Sevag Mekhitarian',
        title: 'GM',
        fideId: '2107669',
        points: 6.5,
        rank: 3,
        buchholz: 47.0,
        sonnebornBerger: 32.5,
        wins: 6
      },
      {
        playerId: 'seed-4',
        playerName: 'Juliana Sayumi Terao',
        title: 'WGM',
        fideId: '2113200',
        points: 6.0,
        rank: 4,
        buchholz: 45.0,
        sonnebornBerger: 28.0,
        wins: 5
      }
    ]
  },
  {
    name: 'Memorial JK de Xadrez Rápido FBX 2026',
    city: 'Brasília',
    state: 'DF',
    startDate: '2026-07-18',
    endDate: '2026-07-19',
    rounds: 7,
    timeControl: 'Rápido (15m + 10s)',
    type: 'rapid',
    status: 'Finalizado',
    arbiters: 'AN Carlos Calleros',
    organizer: 'Federação Brasiliense de Xadrez',
    participants: [],
    standings: [
      {
        playerId: 'seed-7',
        playerName: 'Rafael Duailibe Leitão',
        title: 'GM',
        fideId: '2100290',
        points: 6.5,
        rank: 1,
        buchholz: 38.0,
        sonnebornBerger: 34.0,
        wins: 6
      },
      {
        playerId: 'seed-1',
        playerName: 'Alexandr Fier',
        title: 'GM',
        fideId: '2107138',
        points: 6.0,
        rank: 2,
        buchholz: 37.5,
        sonnebornBerger: 30.5,
        wins: 5
      },
      {
        playerId: 'seed-2',
        playerName: 'Luis Paulo Supi',
        title: 'GM',
        fideId: '2119934',
        points: 5.5,
        rank: 3,
        buchholz: 36.0,
        sonnebornBerger: 27.0,
        wins: 5
      },
      {
        playerId: 'seed-4',
        playerName: 'Kathie Goulart Librelato',
        title: 'WIM',
        fideId: '2124571',
        points: 5.0,
        rank: 4,
        buchholz: 35.0,
        sonnebornBerger: 24.0,
        wins: 4
      },
      {
        playerId: 'seed-6',
        playerName: 'Enzo Federzoni Sakai',
        title: 'FM',
        fideId: '2138904',
        points: 4.5,
        rank: 5,
        buchholz: 33.0,
        sonnebornBerger: 19.5,
        wins: 4
      }
    ]
  },
  {
    name: 'Taça Brasília Standard de Clássico 2026',
    city: 'Brasília',
    state: 'DF',
    startDate: '2026-05-01',
    endDate: '2026-05-04',
    rounds: 6,
    timeControl: 'Pensado (90m + 30s)',
    type: 'standard',
    status: 'Finalizado',
    arbiters: 'AI Marco Antonio Asbahr',
    organizer: 'Federação Brasiliense de Xadrez',
    participants: [],
    standings: [
      {
        playerId: 'seed-7',
        playerName: 'Rafael Duailibe Leitão',
        title: 'GM',
        fideId: '2100290',
        points: 5.5,
        rank: 1,
        buchholz: 30.0,
        sonnebornBerger: 26.5,
        wins: 5
      },
      {
        playerId: 'seed-3',
        playerName: 'Juliana Sayumi Terao',
        title: 'WGM',
        fideId: '2113200',
        points: 5.0,
        rank: 2,
        buchholz: 29.5,
        sonnebornBerger: 23.5,
        wins: 4
      },
      {
        playerId: 'seed-1',
        playerName: 'Alexandr Fier',
        title: 'GM',
        fideId: '2107138',
        points: 4.5,
        rank: 3,
        buchholz: 28.0,
        sonnebornBerger: 21.0,
        wins: 4
      },
      {
        playerId: 'seed-4',
        playerName: 'Kathie Goulart Librelato',
        title: 'WIM',
        fideId: '2124571',
        points: 4.0,
        rank: 4,
        buchholz: 27.5,
        sonnebornBerger: 18.0,
        wins: 3
      },
      {
        playerId: 'seed-youth-1',
        playerName: 'Gabriel de Oliveira Santos',
        title: 'FM',
        fideId: '2160341',
        points: 3.5,
        rank: 5,
        buchholz: 25.0,
        sonnebornBerger: 14.5,
        wins: 3
      }
    ]
  }
];
